// Maestro C3 — NVS-backed persistence.
//
// Two namespaces inside NVS:
//   "wifi"     — STA credentials (optional, for home-network fallback).
//   "player"   — per-clientId profiles { name, color, instrument }.
//
// NVS key length is capped at 15 characters by ESP-IDF, so when we key by
// clientId (a UUID) we hash/truncate to 15 chars. See savePlayerProfile().

#pragma once

#include <Arduino.h>

namespace Persistence {

// One-time begin (called from setup() before any get/save). Safe to call again.
void begin();

// WiFi STA credentials --------------------------------------------------------
bool loadWifiCreds(String& ssid, String& psk);
bool saveWifiCreds(const String& ssid, const String& psk);
bool clearWifiCreds();

// Per-player profile ----------------------------------------------------------
// `clientId` is the UUID generated by the browser and stored in localStorage.
// `name`, `color` (e.g. "#ff8800"), `instrument` (id from instruments.js).
bool loadPlayerProfile(const String& clientId,
                       String&       name,
                       String&       color,
                       String&       instrument);

bool savePlayerProfile(const String& clientId,
                       const String& name,
                       const String& color,
                       const String& instrument);

// Wipe everything (factory reset).
bool clearAll();

} // namespace Persistence
